POST https://node-videos-api-pqnz.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET https://node-videos-api-pqnz.onrender.com/videos
# GET https://node-videos-api-pqnz.onrender.com/videos?search=node Busca com Query Parameters (título com node no nome)

###

PUT https://node-videos-api-pqnz.onrender.com/videos/152bbfee-0020-47f6-82bc-d2d59f943a20
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o segundo vídeo",
    "duration": 180
}

###

DELETE https://node-videos-api-pqnz.onrender.com/videos/152bbfee-0020-47f6-82bc-d2d59f943a20